### ISSUE TITLE
IWYU doesn't work with paths rooted on an environment variable

### ISSUE THREAD

**Issue by degracode** [Wumpf/IncludeToolbox#11]
My project has some include directories that start with an environment variable, eg:
$(DXSDK_DIR)\include
$(ENGINE)\include

These aren't being passed on the command-line to IWYU.

**Comment by Wumpf** [comment]
Odd, for me Visual Studio is correctly resolving all those environment variables. Actually, when asking for the include paths the VS API already returns me a list of fully resolved paths. So it sounds more like VS itself couldn't resolve it.

**Comment by Wumpf** [comment]
@degracode I'm doing some updates for the IWYU integration right now. Do you have any more information? Are you certain those variables weren't resolved? You should see the command line arguments the tool is sending at the beginning of the IncludeToolbox output in the output window.
