### ISSUE TITLE
Failed to retrieve VCCLCompilerTool since project is not a VCProject.

### ISSUE THREAD

**Issue by gulgi** [Wumpf/IncludeToolbox#13]
Choosing "Format Selected Includes" gives me this:
Failed to retrieve VCCLCompilerTool since project is not a VCProject.

**Comment by gulgi** [comment]
Intellisense needs to be enabled. :)

**Comment by Wumpf** [comment]
Oh that's interesting. Didn't know about this dependency :-O
That might be worth looking into...
