### ISSUE TITLE
Try and Error: Builds fail when __LINE__ has been used in macros

### ISSUE THREAD

**Issue by CyberTech** [Wumpf/IncludeToolbox#18]
In certain situations, such as WPP log tracing with wpptrace, an include file will be generated which defines

WPP_FOO_Filename_LineNo

where LineNo is the original line number from the source file. 

Try and Error mode appears to delete the entire line, including the line break.  Because of this, the macros defined by WPP no longer match the source lines -- they're all off by 1.

If Try and Error mode instead cleared the include line (but left the newline intact), or commented out the line, then the build would succeed.

**Comment by Wumpf** [comment]
I'm not familiar with WPP log tracing, but it sounds like you're applying the include removal to an autogenerated file?

Well, I guess I could add an option to keep the line breaks but I hope you understand that I won't make this the default ;)

**Comment by CyberTech** [comment]
Oh, certainly I wouldn't expect it to be the default -- although I'm not sure it'd change the behavior during the test cycle.

As far as applying the include removal to the generated file, no, that'd be silly :)

Thanks for making the change -- I'll include the rest here in case you're curious about why.

WPP log trace is how Microsoft recommends release mode log tracing is performed, especially in drivers and such.  It allows logging to be performed without formatting or context, with simply a minimal encoded ID.  After the fact, tools take the information from the PDB and turn the binary log into a full log that could have come from printf and friends.

Foo.cpp
#include "foo.cpp.tmh"
// The TMH file is auto-generated by tracewpp, on a PreBuild event, based on the contents of this file

WPP_TRACE(....)

----------
The WPP_TRACE macro is defined as varying forms, but once of the common forms is:
#define WPP_(Id) WPP_EVAL(WPP_) ## WPP_EVAL(Id) ## WPP_EVAL(_) ## WPP_EVAL(WPP_THIS_FILE) ## WPP_EVAL(__LINE__)

Note the __LINE__ appended to the end.  inside Foo.cpp.tmh, there is a corresponding define, generated by wpptrace:
  #define WPP_ANNOTATE_Foo_cpp10005
^ where 10005 is the line that made the WPP logging call at the time tracewpp was called.

So, line 10005 is hard-coded in the TMH file, which is fine as long as all builds happen with project->build -- because then pre-build events happen, and the TMH file is re-written.  If it's not re-written, as is the case here, instead the CPP file tries to resolve WPP_ANNOTATE_FOO_cpp_10004, and fails.

But, in this case, it's just compile-current-file, and the WPP info is not regenerated on a individual-file basis (nor should it be, there's a noticable startup time for the tool)

**Comment by Wumpf** [comment]
Thank you very much for the explanation! Didn't know about it, very interesting :)
