### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kravlost** [Wumpf/IncludeToolbox#35]
This feels like a petty complaint for a great extension, but could the menus be changed to "Trial and error"? ([Trial and error](https://en.wikipedia.org/wiki/Trial_and_error))

**Comment by Wumpf** [comment]
Oh my. You're right, I got it all wrong! Well at least I had it consistent everywhere :D
Thanks for pointing that out :)

**Comment by kravlost** [comment]
No problem. :) Thanks for this extension, it saves hours of manual include pruning!

**Comment by Wumpf** [comment]
Fixed on repository, will upload a new version probably next week.

**Comment by kravlost** [comment]
Great, thanks!
