### ISSUE TITLE
Comment tag to avoid removing include in iwyu & trial and error removal

### ISSUE THREAD

**Issue by Wumpf** [Wumpf/IncludeToolbox#38]
See Q&A by _Ergin Salih_ https://marketplace.visualstudio.com/items?itemName=Wumpf.IncludeToolbox#qna

> Have you considered adding an option where you can tag an include file (in a preceding comment) so that it is not considered for removal in a specific CPP file.  I had a issue where an include file was removed because the CPP file compiled but the code did not run correctly.

**Comment by ergins23** [comment]
How about something like this.

`#include "tokenizer.h" // $include-toolbox-ignore$`
or ...
`#include "tokenizer.h" // $include-toolbox-preserve$`

That way if you had more options then you just keep adding them to the end of the line.
