### ISSUE TITLE
Can't run IWYU: Couldn't file a VCCLCompilerTool in VC++ Project.

### ISSUE THREAD

**Issue by parkpd** [Wumpf/IncludeToolbox#61]
I installed IncludeToolbox to VisualStudio 2017 professional.
And download include-what-you-use.exe from https://github.com/Wumpf/iwyu_for_vs_includetoolbox
When I run by Rclick -> 'Run Include-What-You-Use', it says 'there is a newer version...' , and download it, then it makes error popup.
'Include Toolbox
Can't run IWYU: Couldn't file a VCCLCompilerTool in VC++ Project.'
What should I do next?
Sincere Ryan.

**Comment by Wumpf** [comment]
According to the message (which has a typo - should be "Couldn't find") you are not executing the action on a C++ project. Is that the case?
