### ISSUE TITLE
Unable to build the vsix plugin in VS2017

### ISSUE THREAD

**Issue by pjwhams** [Wumpf/IncludeToolbox#66]
I've created a fork https://github.com/pjwhams/IncludeToolbox/ in order to try building a version of the addin that will load in VS2019.  I'm building in VS2017.  I've fixed up some of the project references and it's building the .dll but for some reason it's not generating the .vsix file. I really have no idea why - there are no warnings and all the project settings look ok.  Any idea why this is happening?  PR: #68

**Comment by Wumpf** [comment]
Starting with #69 building is only supported in VS2019
