### ISSUE TITLE
Download link in visual studio gallery doesn't work

### ISSUE THREAD

**Issue by dakotahawkins** [Wumpf/IncludeToolbox#7]
It appears to just refresh the page.

**Comment by Wumpf** [comment]
Happens with all plugins in the Visual Studio Gallery at the moment. Reuploading didn't solve the problem

**Comment by dakotahawkins** [comment]
Ah that's unfortunate. I wonder if they're finally pushing the migration to the new page interface.

**Comment by dakotahawkins** [comment]
If you browse to it through the beta interface, you get to [this page](https://visualstudiogallery.msdn.microsoft.com/28c36d4f-425a-4bfe-9449-03f07b35f7b0) which is different from the link in your readme, and that link does work. Not sure if they'll fix it or if it's worth updating the readme or what.

**Comment by Wumpf** [comment]
Nice find. Will update the readme.

**Comment by dakotahawkins** [comment]
Might be worth putting the link on the gallery page too, something like "download doesn't work? try it from here".
