### ISSUE TITLE
IWYU "Apply Proposal" is slightly broken

### ISSUE THREAD

**Issue by dakotahawkins** [Wumpf/IncludeToolbox#9]
Unfortunately I can not share the case, but I can describe it.

The IWYU output is correct (for it) in terms of the "The full include-list for ..." ouptut, however IncludeToolbox winds up removing some of the includes in that output.

I suspect it is just a bug in the editing logic. I'll look in to it if I have some time, however my suggestion is:

IWYU tells you which lines to delete, but not where to add new ones, so I would instead take it's output from "The full include list for..." and assume they go at the top of the file. Delete all includes and insert the list where the first one was.

Another related issue is that suggestions for forward declarations aren't parsed or handled. It could perhaps be easier on this extension to take the suggested end-state as canonical and replace anything that looks like an include OR forward declaration.

**Comment by Wumpf** [comment]
After I realized that IWYU's outputs are mostly broken for all projects where I wanted to use it, I didn't put too much effort into that feature. I thought the code would just put the entire incl+predecl block after the last include it found. Didn't check though.
I'll have a look at it next weekend.

**Comment by dakotahawkins** [comment]
It does take some manual tweaking of its output for me, but it's the closest to correct I've seen on Windows. I think maybe it could get a lot better with tweaks to its options, but it's also possible the easiest way to get it to work would be to make your code compile with clang without error.

**Comment by Wumpf** [comment]
Ahh I kinda lost track of that issue. I cannot promise anything but it is still on one of my todo lists!

**Comment by dakotahawkins** [comment]
What we really need to do is make mapping files for MSVC. I'm not sure the best way to go about it though. It would be nice to have an offline copy of their documentation so you could grep suggested include files for individual symbols, it looks kind-of like that's how most of the gcc maps are generated/maintained.

**Comment by Wumpf** [comment]
Docs on mapping files: https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md

**Comment by Wumpf** [comment]
There are now also mappings files that are downloaded and automatically put into the config from https://github.com/Wumpf/iwyu_for_vs_includetoolbox
Doesn't cover much yet, but it's a start.
